services:
  postgres:
    image: postgres:16-alpine
    container_name: olist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: olist
      POSTGRES_USER: olist
      POSTGRES_PASSWORD: olist123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  n8n:
    image: n8nio/n8n
    container_name: olist_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./src:/home/node/scripts
      - ./data:/home/node/data
    depends_on:
      - postgres

volumes:
  pgdata:
  n8n_data: